# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  VERSION:
    sh: git describe --tags --always --dirty || echo dev
  OUTPUT_DIR: bin

tasks:
  build:
    cmds:
      - task: build-his
      - task: build-bm
      - task: build-zox
      - task: build-launcher
  build-his:
    cmds:
      - go build -ldflags="-s -w -X main.version={{.VERSION}}" -o {{.OUTPUT_DIR}}/afxw-his.exe ./cmd/afxw-his
  build-bm:
    cmds:
      - go build -ldflags="-s -w -X main.version={{.VERSION}}" -o {{.OUTPUT_DIR}}/afxw-bm.exe ./cmd/afxw-bm
  build-zox:
    cmds:
      - go build -ldflags="-s -w -X main.version={{.VERSION}}" -o {{.OUTPUT_DIR}}/afxw-zox.exe ./cmd/afxw-zox
  build-launcher:
    cmds:
      - go build -ldflags="-s -w -X main.version={{.VERSION}}" -o {{.OUTPUT_DIR}}/afxw-launcher.exe ./cmd/afxw-launcher
  lint:
    cmds:
      - golangci-lint run ./...
  test:
    cmds:
      - go test ./...
  integration-test:
    cmds:
      - go test -tags=integration ./...
